spring:
  application:
    name: auth-service

jwt:
  secret: secretKeyAnything1234567890abcdefghijklmnopqrstuvwxyz

logging:
  level:
    root: debug


# Hardcoded users (For simplicity, in a real application you should use encrypted passwords and an external storage)
app:
  user-details: user1#password1#123,user2#password2#234,user3#password3#345,system#systemPassword#000

