gitkspring:
  application:
    name: asset-service
  datasource:
    url: jdbc:mysql://mysql:3306/database_name?allowPublicKeyRetrieval=true&useSSL=FALSE&serverTimezone=UTC
    username: root
    password: root_password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

logging:
  level:
    com.spot: DEBUG
